spring:
  application:
    name: wavy

  datasource:
    url: jdbc:postgresql://localhost:5432/yoruwavy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernation:
      ddl-auto: update
    show-sql: true

server:
  port: 8088